
export const SEND_ORDER_REQUEST:'SEND_ORDER_REQUEST' = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS:'SEND_ORDER_SUCCESS' = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED:'SEND_ORDER_FAILED' = "SEND_ORDER_FAILED";

export const SHOW_MODAL_INFO_ORDER:'SHOW_MODAL_INFO_ORDER' = "SHOW_MODAL_INFO_ORDER"
export const HIDE_MODAL_INFO_ORDER:'HIDE_MODAL_INFO_ORDER' = "HIDE_MODAL_INFO_ORDER"
